In [3]:
import numpy as np

In [4]:
matriz1 = np.random.randn(8,3)
matriz2 = np.random.randn(8,3)

In [5]:
np.add(matriz1, matriz2)

array([[ 1.25209699, -0.32331585,  0.89129323],
       [-1.26238605,  1.92521667,  1.05294079],
       [ 0.40782836,  1.48237553, -0.90033213],
       [ 0.91186051,  0.74103826,  0.56819762],
       [ 0.36345037, -1.62616329,  1.05805412],
       [ 1.5500312 ,  1.64774671,  0.36469786],
       [-1.59736002, -2.82203446, -0.47282847],
       [ 1.20671494, -0.24519236, -1.38952442]])

In [6]:
np.matmul(matriz1.T, matriz2)

array([[ 1.47607873,  2.22929446, -2.63233225],
       [-0.43744287, -0.29407161, -2.61191165],
       [ 0.54493772,  3.42271734, -0.07570791]])

In [7]:
np.negative(matriz1)

array([[-0.8940358 ,  0.19496544, -0.85112218],
       [ 1.06158629, -1.13550926,  0.12366004],
       [-0.50876012, -1.92934687,  0.39815501],
       [-1.26738797,  0.12334115, -0.89057135],
       [ 0.02781769,  2.52397167, -0.03874153],
       [-1.14719168, -0.71838178, -0.43207508],
       [ 0.70850199,  0.66506161,  0.88394739],
       [-0.58564677, -0.19042913,  0.77790156]])

In [8]:
np.mod(matriz1, matriz2)

array([[ 0.17791341, -0.06661504,  0.00752997],
       [-0.05758749,  0.34580184,  1.05294079],
       [-0.09683046, -0.3055098 , -0.39815501],
       [-0.15472187,  0.74103826, -0.07654985],
       [ 0.36345037,  0.16945348,  0.03874153],
       [ 0.34151264,  0.71838178, -0.03956542],
       [-0.70850199, -0.66506161,  0.34940936],
       [ 0.58564677, -0.24519236, -0.16627871]])

In [9]:
np.absolute(matriz1)

array([[0.8940358 , 0.19496544, 0.85112218],
       [1.06158629, 1.13550926, 0.12366004],
       [0.50876012, 1.92934687, 0.39815501],
       [1.26738797, 0.12334115, 0.89057135],
       [0.02781769, 2.52397167, 0.03874153],
       [1.14719168, 0.71838178, 0.43207508],
       [0.70850199, 0.66506161, 0.88394739],
       [0.58564677, 0.19042913, 0.77790156]])

In [10]:
np.rint(matriz1) #round int

array([[ 1., -0.,  1.],
       [-1.,  1., -0.],
       [ 1.,  2., -0.],
       [ 1., -0.,  1.],
       [-0., -3.,  0.],
       [ 1.,  1.,  0.],
       [-1., -1., -1.],
       [ 1.,  0., -1.]])

In [11]:
array7 = np.array([2.52, 3.42, 1.85, 2.95, 3.95, 3.78, 3.17, 3.96, 2.97, 2.98,
3.35, 4.23, 3.42, 4.60, 5.24, 3.64, 4.54, 4.81, 1.77, 1.51, 3.08, 2.00])
#Colocando em ordem
print(np.sort(array7))

[1.51 1.77 1.85 2.   2.52 2.95 2.97 2.98 3.08 3.17 3.35 3.42 3.42 3.64
 3.78 3.95 3.96 4.23 4.54 4.6  4.81 5.24]


In [12]:
-np.sort(-array7)

array([5.24, 4.81, 4.6 , 4.54, 4.23, 3.96, 3.95, 3.78, 3.64, 3.42, 3.42,
       3.35, 3.17, 3.08, 2.98, 2.97, 2.95, 2.52, 2.  , 1.85, 1.77, 1.51])

In [13]:
print(sorted(array7, reverse=True))

[5.24, 4.81, 4.6, 4.54, 4.23, 3.96, 3.95, 3.78, 3.64, 3.42, 3.42, 3.35, 3.17, 3.08, 2.98, 2.97, 2.95, 2.52, 2.0, 1.85, 1.77, 1.51]


In [14]:
matriz = np.array([[1, 4], [3, 1]])
print(matriz)
print(np.sort(matriz, axis = 1)) #Ordena as colunas
print(np.sort(matriz, axis = 0)) #Ordena as linhas

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]
[[1 1]
 [3 4]]


In [16]:
nomes = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(nomes))
numeros = np.array([3, 3, 2, 2, 1, 1, 1, 4, 4])
print(np.unique(numeros))

['Bob' 'Joe' 'Will']
[1 2 3 4]
