# Lista de Exercícios: NumPy

## Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1 

In [1]:
#Importe a biblioteca NumPy para seu Notebook
import numpy as np

### Exercício 2

In [34]:
#Compare a velocidade, da operação a seguir, entre uma lista de Python Puro e um ndarray do NumPy com 1 bilhão de elementos
#
#Eleve a potência quadrática cada elemento do ndarray e da lista e exiba o tempo de execução de cada um dos objetos
lista = range(10000000)
vetor = np.arange(10000000)
%time for _ in range(10): vetor = vetor ** 2

Wall time: 129 ms


In [35]:
%time for _ in range(10): lista2 = [x ** 2 for x in lista]

Wall time: 22.3 s


### Exercício 3

In [4]:
#Crie uma matriz de cinco linhas e três colunas
#Calcule a Raiz Quadrada dos elementos da matriz de uma única vez
matriz = np.random.randint(1, 100, size=(5, 3))
matriz

array([[24, 80, 92],
       [37, 56, 34],
       [55, 49, 84],
       [ 9, 51, 63],
       [45, 46, 24]])

In [5]:
matriz ** 0.5

array([[4.89897949, 8.94427191, 9.59166305],
       [6.08276253, 7.48331477, 5.83095189],
       [7.41619849, 7.        , 9.16515139],
       [3.        , 7.14142843, 7.93725393],
       [6.70820393, 6.78232998, 4.89897949]])

### Exercício 4

In [6]:
#Crie as matrizes a seguir e verifique suas propriedades (formato, tipo e número de dimensões)
import numpy as np
matriz1 = np.random.rand(8, 5)
matriz2 = np.array([[7., 8, 9, 10.98], [65, 42, 3, 18]])
matriz3 = np.array([[1, "2", "4.5", 7], [4, "18", 14, "3"]], dtype=np.string_)

In [7]:
for m in [matriz1, matriz2, matriz3]:
    print(m.shape)
    print(m.ndim)
    print(m.dtype)
    print()

(8, 5)
2
float64

(2, 4)
2
float64

(2, 4)
2
|S3



### Exercício 5

In [8]:
#Crie uma ndarray de 3x4 do tipo float e converta para:
#(1) int
#(2) string
mat_float = np.random.randn(3,4)
mat_float.dtype

dtype('float64')

In [9]:
mat_int = mat_float.astype(int)
mat_int.dtype

dtype('int32')

In [10]:
mat_str = mat_int.astype(str)
mat_str.dtype

dtype('<U11')

### Exercício 6

In [11]:
#Crie um ndarray com 100 números aleatórios
#Acesse o 32º elemento
#Altere os índices de 18 a 31 para 128
#Copie o ndarray para um novo ndarray
#Exiba o primeiro ndarray
#Altere o segundo ndarray modificando os índices de 18 a 32 para 256
#Exiba o segundo ndarray

In [12]:
vetor6 = np.random.randn(50)
print(vetor6[31])
print(vetor6[18:32])

-3.3909785156622867
[ 1.61457875  1.27342993  0.50798255 -1.59331105  0.64317022  0.08719566
 -0.28821396 -0.01729953  0.56239909  0.92745953 -0.78192955  1.03180649
  0.50954081 -3.39097852]


In [13]:
vetor6[18:32] = 128
vetor6_copy = vetor6.copy() 
print(vetor6)

[ 1.02255169e+00  1.19539032e+00 -1.18987816e+00  1.48386690e+00
 -2.36908877e+00  7.68239758e-01  5.61379506e-01 -6.68145577e-01
 -7.24431369e-01 -1.53687550e+00  9.48687407e-01 -3.66944510e-01
 -8.00058974e-01  7.62695317e-01  9.92049558e-02  1.29474694e-01
 -6.19678343e-01 -1.01776601e+00  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
 -1.31697965e+00 -1.93057453e+00 -5.18597982e-01 -2.20668214e-02
 -1.45854190e+00  7.98358959e-01  1.20349888e+00 -2.08726362e+00
 -7.13711838e-01 -1.27271804e+00  6.37113116e-01  8.05373835e-01
 -1.85183811e+00  1.59133851e+00 -9.78414079e-01 -1.15704081e+00
  1.12078420e+00  1.31875989e-02]


In [14]:
print(vetor6_copy)

[ 1.02255169e+00  1.19539032e+00 -1.18987816e+00  1.48386690e+00
 -2.36908877e+00  7.68239758e-01  5.61379506e-01 -6.68145577e-01
 -7.24431369e-01 -1.53687550e+00  9.48687407e-01 -3.66944510e-01
 -8.00058974e-01  7.62695317e-01  9.92049558e-02  1.29474694e-01
 -6.19678343e-01 -1.01776601e+00  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
 -1.31697965e+00 -1.93057453e+00 -5.18597982e-01 -2.20668214e-02
 -1.45854190e+00  7.98358959e-01  1.20349888e+00 -2.08726362e+00
 -7.13711838e-01 -1.27271804e+00  6.37113116e-01  8.05373835e-01
 -1.85183811e+00  1.59133851e+00 -9.78414079e-01 -1.15704081e+00
  1.12078420e+00  1.31875989e-02]


In [15]:
vetor6_copy[18:32] = 256
print(vetor6)

[ 1.02255169e+00  1.19539032e+00 -1.18987816e+00  1.48386690e+00
 -2.36908877e+00  7.68239758e-01  5.61379506e-01 -6.68145577e-01
 -7.24431369e-01 -1.53687550e+00  9.48687407e-01 -3.66944510e-01
 -8.00058974e-01  7.62695317e-01  9.92049558e-02  1.29474694e-01
 -6.19678343e-01 -1.01776601e+00  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
  1.28000000e+02  1.28000000e+02  1.28000000e+02  1.28000000e+02
 -1.31697965e+00 -1.93057453e+00 -5.18597982e-01 -2.20668214e-02
 -1.45854190e+00  7.98358959e-01  1.20349888e+00 -2.08726362e+00
 -7.13711838e-01 -1.27271804e+00  6.37113116e-01  8.05373835e-01
 -1.85183811e+00  1.59133851e+00 -9.78414079e-01 -1.15704081e+00
  1.12078420e+00  1.31875989e-02]


In [16]:
print(vetor6_copy)

[ 1.02255169e+00  1.19539032e+00 -1.18987816e+00  1.48386690e+00
 -2.36908877e+00  7.68239758e-01  5.61379506e-01 -6.68145577e-01
 -7.24431369e-01 -1.53687550e+00  9.48687407e-01 -3.66944510e-01
 -8.00058974e-01  7.62695317e-01  9.92049558e-02  1.29474694e-01
 -6.19678343e-01 -1.01776601e+00  2.56000000e+02  2.56000000e+02
  2.56000000e+02  2.56000000e+02  2.56000000e+02  2.56000000e+02
  2.56000000e+02  2.56000000e+02  2.56000000e+02  2.56000000e+02
  2.56000000e+02  2.56000000e+02  2.56000000e+02  2.56000000e+02
 -1.31697965e+00 -1.93057453e+00 -5.18597982e-01 -2.20668214e-02
 -1.45854190e+00  7.98358959e-01  1.20349888e+00 -2.08726362e+00
 -7.13711838e-01 -1.27271804e+00  6.37113116e-01  8.05373835e-01
 -1.85183811e+00  1.59133851e+00 -9.78414079e-01 -1.15704081e+00
  1.12078420e+00  1.31875989e-02]


### Exercício 7

In [17]:
#Crie a matriz abaixo
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])
#Selecione através dos índices os itens 5, 6 e 7
#Selecione através dos índices os itens 7, 11 e 15
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
arr2d[1:2,:3]

array([[5, 6, 7]])

In [19]:
arr2d[1:,2:3]

array([[ 7],
       [11],
       [15]])

### Exercício 8

In [20]:
#Crie uma lista com os nomes: Antônio, Carlos, Carlos, Antônio, José, Alfredo, Alfredo, Antônio
#Crie uma lista chamada dívidas com os seguintes valores: 1000., 500., 0, 1640, 18399.99, 42640.18, 70., 84.90
#Busque na lista de nomes as ocorrências de Antônio e exiba suas dívidas
#Busque na lista de nomes as ocorrências de José e exiba suas dívidas
#Exiba as dívidas das pessoas diferente de Antônio e José
#Exiba os nomes das pessoas que possuem dívidas igual a 0 (zero)
#Exiba os nomes das pessoas que possuem dívidas maior que 10000 (dez mil)
#Exiba os nomes das pessoas que possuem dívidas menores que 100 (cem) e maior do que 0 (zero)

In [21]:
nomes = np.array(['Antônio', 'Carlos', 'Carlos', 
                  'Antônio', 'José', 'Alfredo', 
                  'Alfredo', 'Antônio'])
dividas = np.array([1000., 500., 0, 1640, 
                    18399.99, 42640.18, 70., 
                    84.90])

In [22]:
dividas[nomes == "Antônio"]

array([1000. , 1640. ,   84.9])

In [23]:
dividas[nomes == "José"]

array([18399.99])

In [24]:
dividas[(nomes != "Antônio") & (nomes != "José")]

array([  500.  ,     0.  , 42640.18,    70.  ])

In [25]:
nomes[dividas == 0]

array(['Carlos'], dtype='<U7')

In [26]:
nomes[dividas > 10000]

array(['José', 'Alfredo'], dtype='<U7')

In [36]:
nomes[(dividas > 0) & (dividas < 100)]

['Alfredo' 'Antônio']


### Exercício 9

In [28]:
#Ordene e exiba a lista de nomes criado no execício anterior
#Ordene em ordem decrescente e exiba a lista de valores criado no execício anterior

In [29]:
np.sort(nomes)

array(['Alfredo', 'Alfredo', 'Antônio', 'Antônio', 'Antônio', 'Carlos',
       'Carlos', 'José'], dtype='<U7')

In [30]:
-np.sort(-dividas)

array([42640.18, 18399.99,  1640.  ,  1000.  ,   500.  ,    84.9 ,
          70.  ,     0.  ])

### Exercício 10

In [31]:
#Exiba os valores únicos das listas criadas no exercício 8

In [32]:
np.unique(nomes)

array(['Alfredo', 'Antônio', 'Carlos', 'José'], dtype='<U7')

In [33]:
np.unique(dividas)

array([    0.  ,    70.  ,    84.9 ,   500.  ,  1000.  ,  1640.  ,
       18399.99, 42640.18])