In [2]:
import numpy as np
import random as random

In [3]:
nparray = np.arange(100000000)
lista = range(100000000)

In [4]:
%time np.square(nparray)

CPU times: total: 93.8 ms
Wall time: 100 ms


array([         0,          1,          4, ..., 1274919433, 1474919428,
       1674919425])

In [6]:
%time lista2 = [x**2 for x in lista]

CPU times: total: 4.92 s
Wall time: 5.96 s


In [7]:
matriz = np.random.randint(0, 10, (5,3))
print(matriz)

[[4 9 5]
 [6 4 6]
 [8 8 4]
 [1 3 0]
 [0 8 8]]


In [10]:
np.sqrt(matriz)

array([[2.        , 3.        , 2.23606798],
       [2.44948974, 2.        , 2.44948974],
       [2.82842712, 2.82842712, 2.        ],
       [1.        , 1.73205081, 0.        ],
       [0.        , 2.82842712, 2.82842712]])

In [12]:
import numpy as np
matriz1 = np.random.rand(8, 5)
matriz2 = np.array([[7., 8, 9, 10.98], [65, 42, 3, 18]])
matriz3 = np.array([[1, "2", "4.5", 7], [4, "18", 14, "3"]], dtype=np.string_)

In [20]:
for x in [matriz1, matriz2, matriz3]:
    print(x.shape)
    print(x.ndim)
    print(x.dtype)
    print()

(8, 5)
2
float64

(2, 4)
2
float64

(2, 4)
2
|S3



In [22]:
mat_float = np.random.randn(3,4)
mat_float.dtype

dtype('float64')

In [24]:
mat_int = mat_float.astype(int)
mat_int.dtype

dtype('int32')

In [27]:
mat_str = mat_float.astype(str)
mat_str.dtype

dtype('<U32')

In [50]:
array = np.random.randint(1,101, (100))
array

array([ 23,  46,  10,  64,  35,  61,  37,  73,   9,  86,  95,  74,  39,
        25,  57,  71,  88,  17,  11,  52,  90,  89,  60,  28,  49,  98,
        26,  65,  96,  10,  12,  45,  90,  58,  49,  48,  64,  50,  99,
        24,  80,  90,  46,  44,  27,  13,  67,  96,  72,  95, 100,  57,
        24,  15,  21,  16,  43,  95,  88,  61,  93,   1,  31,  11,  66,
        18,  16,  17,   3,  56,  63,  11,   8,  59,  30,  73,  45,  47,
        89,   1,  95,  48,  56,  99,   4,  57,  75,  62,  13,  62,  84,
        57,  27,  87,   1,  46,  23,  13,  97,  46])

In [52]:
print(array[31])

45


In [53]:
array[18:32] = 128
array

array([ 23,  46,  10,  64,  35,  61,  37,  73,   9,  86,  95,  74,  39,
        25,  57,  71,  88,  17, 128, 128, 128, 128, 128, 128, 128, 128,
       128, 128, 128, 128, 128, 128,  90,  58,  49,  48,  64,  50,  99,
        24,  80,  90,  46,  44,  27,  13,  67,  96,  72,  95, 100,  57,
        24,  15,  21,  16,  43,  95,  88,  61,  93,   1,  31,  11,  66,
        18,  16,  17,   3,  56,  63,  11,   8,  59,  30,  73,  45,  47,
        89,   1,  95,  48,  56,  99,   4,  57,  75,  62,  13,  62,  84,
        57,  27,  87,   1,  46,  23,  13,  97,  46])

In [61]:
array1 = array.copy()
array1

array([ 23,  46,  10,  64,  35,  61,  37,  73,   9,  86,  95,  74,  39,
        25,  57,  71,  88,  17, 128, 128, 128, 128, 128, 128, 128, 128,
       128, 128, 128, 128, 128, 128,  90,  58,  49,  48,  64,  50,  99,
        24,  80,  90,  46,  44,  27,  13,  67,  96,  72,  95, 100,  57,
        24,  15,  21,  16,  43,  95,  88,  61,  93,   1,  31,  11,  66,
        18,  16,  17,   3,  56,  63,  11,   8,  59,  30,  73,  45,  47,
        89,   1,  95,  48,  56,  99,   4,  57,  75,  62,  13,  62,  84,
        57,  27,  87,   1,  46,  23,  13,  97,  46])

In [57]:
array

array([ 23,  46,  10,  64,  35,  61,  37,  73,   9,  86,  95,  74,  39,
        25,  57,  71,  88,  17, 128, 128, 128, 128, 128, 128, 128, 128,
       128, 128, 128, 128, 128, 128,  90,  58,  49,  48,  64,  50,  99,
        24,  80,  90,  46,  44,  27,  13,  67,  96,  72,  95, 100,  57,
        24,  15,  21,  16,  43,  95,  88,  61,  93,   1,  31,  11,  66,
        18,  16,  17,   3,  56,  63,  11,   8,  59,  30,  73,  45,  47,
        89,   1,  95,  48,  56,  99,   4,  57,  75,  62,  13,  62,  84,
        57,  27,  87,   1,  46,  23,  13,  97,  46])

In [63]:
array1[18:32] = 256
array1

array([ 23,  46,  10,  64,  35,  61,  37,  73,   9,  86,  95,  74,  39,
        25,  57,  71,  88,  17, 256, 256, 256, 256, 256, 256, 256, 256,
       256, 256, 256, 256, 256, 256,  90,  58,  49,  48,  64,  50,  99,
        24,  80,  90,  46,  44,  27,  13,  67,  96,  72,  95, 100,  57,
        24,  15,  21,  16,  43,  95,  88,  61,  93,   1,  31,  11,  66,
        18,  16,  17,   3,  56,  63,  11,   8,  59,  30,  73,  45,  47,
        89,   1,  95,  48,  56,  99,   4,  57,  75,  62,  13,  62,  84,
        57,  27,  87,   1,  46,  23,  13,  97,  46])

In [65]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
arr2d[1:2, :3]

array([[5, 6, 7]])

In [73]:
arr2d[1:,2:3]

array([[ 7],
       [11],
       [15]])